apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
  namespace: keycloak
spec:
  db:
    host: postgres-db
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    hostname: KEYCLOAK_URL
  http:
    tlsSecret: rhbk-tls-secret
  ingress:
    className: openshift-default
  instances: 1
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: http-relative-path
      value: /auth 
